name: Scan Rules DB and Namespaces
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  scan_job:
    name: Scanner Registry Action
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Registry
        uses: boostsecurityio/scanner-registry-action@86cdcced54a9ef7865954ac50d176baa0a1b9ba6 # v1.0.2
        with:
          api_token: ${{ secrets.BOOST_SYSTEM_API_KEY_REGISTRY_DEV }}
          api_endpoint: https://api.dev.boostsec.io
          docs_url: https://docs.dev.boostsec.io
